#ifndef APPCONFIG_H
#define APPCONFIG_H 

#define APPCONFIG_TITLE "Breakout"
#define APPCONFIG_WINDOW_WIDTH 800
#define APPCONFIG_WINDOW_HEIGHT 600 


#define APPCONFIG_BG_COLOR (Color){13, 25, 32, 255}



#endif 
